apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ec2
  namespace: argocd
  labels:
    name: app-ec2
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  project: default
  source:
    repoURL: https://github.com/CloudOpsDemos/crossplane-prep.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: ec2-deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
