kind: Secret
apiVersion: v1
metadata:
    name: aws-secret
    namespace: crossplane-system
type: Opaque
data:
    creds: <sops encrypted aws_creds>
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:<aws-account-id>:key/<kms_key_id>
          created_at: 
          enc: 
          aws_profile: 
    lastmodified: 
    mac: 
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
