kind: ServiceAccount
apiVersion: v1
metadata:
  name: operator-config-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-config-clusterrole
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "bind", "escalate"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-config-clusterrolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: operator-config-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: operator-config-clusterrole
  apiGroup: rbac.authorization.k8s.io
---