apiVersion: v1
kind: Secret
metadata:
    name: github-creds
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repo-creds
stringData:
    url: <sops encrypted GitHub repo URL>
    type: <sops encrypted type>
    githubAppID: <sops encrypted app ID>
    githubAppInstallationID: <sops encrypted installation ID>
    githubAppPrivateKey: <sops encrypted private key>
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:<aws_account_id>:key/<kms_key_id>
          created_at:
          enc: 
          aws_profile:
    lastmodified: 
    mac: 
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
