apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  labels:
    argocd.argoproj.io/app-name: crossplane
    argocd.argoproj.io/managed-by: argocd
    argocd.argoproj.io/part-of: system-applications
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-applications
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.20.0
    chart: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5